server.port=8080
spring.application.name=api-gateway-service

# Debug logging
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.cors=TRACE
