server.port=${PORT:8080}
spring.application.name=api-gateway-service

spring.mvc.dispatch-options-request=true

# Preserve host header for OAuth2 redirects
spring.cloud.gateway.proxy.preserve-host-header=true

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Auth Service - Login/Register
spring.cloud.gateway.mvc.routes[0].id=auth-service-auth
spring.cloud.gateway.mvc.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**

# Auth Service - OAuth2 start
spring.cloud.gateway.mvc.routes[1].id=auth-service-oauth2
spring.cloud.gateway.mvc.routes[1].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/oauth2/**

# Auth Service - OAuth2 callback
spring.cloud.gateway.mvc.routes[2].id=auth-service-login-oauth2
spring.cloud.gateway.mvc.routes[2].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/login/oauth2/**

# QMA Service
spring.cloud.gateway.mvc.routes[3].id=qma-service
spring.cloud.gateway.mvc.routes[3].uri=${QMA_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/quantities/**

# CORS
spring.web.cors.allowed-origins-patterns=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://quantity-measurement-app-frontend-opal.vercel.app}
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true